installToolDeps: true
tools:
  xcode-dev-tools:
    checkCommand: xcode-select -p
    command: xcode-select --install
  brew:
    script: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh
    postInstall: eval "$(/opt/homebrew/bin/brew shellenv)"
  jq:
    version: "1.6"
    versionCommand: jq --version | awk -F '-' '{ print $2 }'
    checkBrew: true
    brew: {}
  yq:
    version: "4.44.3"
    versionCommand: yq --version 2>&1 | awk '{ print $4 }' | sed 's/v//'
    checkBrew: true
    brew: {}
  json5:
    brew: {}
toolDeps:
  - xcode-dev-tools
  - brew
  - jq
  - yq
  - json5
