installToolDeps: true
tools:
  jq:
    version: "1.6"
    versionCommand: jq --version | awk -F '-' '{ print $2 }'
    checkBrew: true
    brew: {}
  yq:
    version: "4.44.3"
    versionCommand: yq --version 2>&1 | awk '{ print $4 }' | sed 's/v//'
    checkBrew: true
    brew: {}
  json5:
    brew: {}
toolDeps:
  - jq
  - yq
  - json5
