# directory where you store your dotfiles (absolute path)
dotfilesDir:
# directory you clone git repositories to (absolute path)
projectDir:
# whether to automatically install missing tool dependencies
installToolDeps: false
# custom configuration for modules
moduleConfig:
