# directory where you store your dotfiles (absolute path)
dotfilesDir:
# directory you clone git repositories to (absolute path)
projectDir:
# whether to check for missing tool dependencies
checkTools: false
# whether to automatically install missing tool dependencies
installToolsDeps: false
